name: CI - Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Type check
      run: npm run type-check
      
    - name: Lint code
      run: npm run lint
      
    - name: Format check
      run: npm run format:check
      
    - name: Build application
      run: npm run build
      
    - name: Test build output
      run: |
        ls -la dist/
        echo "✅ Build completed successfully!"
        
  # Этот job запустится только после настройки секретов
  deploy-info:
    name: Deployment Info
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Deployment Instructions
      run: |
        echo "🚀 Build completed successfully!"
        echo ""
        echo "📋 To enable automatic deployment to Vercel:"
        echo "1. Go to GitHub Repository Settings → Secrets and variables → Actions"
        echo "2. Add the following secrets:"
        echo "   - VERCEL_TOKEN (from Vercel Dashboard → Settings → Tokens)"
        echo "   - VERCEL_ORG_ID (run 'vercel env ls' in project folder)"
        echo "   - VERCEL_PROJECT_ID (run 'vercel env ls' in project folder)"
        echo ""
        echo "📖 Or deploy manually:"
        echo "   - Visit: https://vercel.com/new/clone?repository-url=https://github.com/Richbanker/Finance-Mini-App"
        echo "   - Click 'Deploy' button"
        echo ""
        echo "✨ Your app is ready for production!"
