name: Deploy to Vercel

# Этот workflow запустится только после настройки секретов
on:
  push:
    branches: [ main, master ]

jobs:
  # Проверяем наличие секретов
  check-secrets:
    name: Check Deployment Secrets
    runs-on: ubuntu-latest
    outputs:
      has-secrets: ${{ steps.check.outputs.has-secrets }}
    steps:
    - name: Check for Vercel secrets
      id: check
      run: |
        if [[ -n "${{ secrets.VERCEL_TOKEN }}" && -n "${{ secrets.VERCEL_ORG_ID }}" && -n "${{ secrets.VERCEL_PROJECT_ID }}" ]]; then
          echo "has-secrets=true" >> $GITHUB_OUTPUT
        else
          echo "has-secrets=false" >> $GITHUB_OUTPUT
        fi

  # Деплой только если секреты настроены
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: check-secrets
    if: needs.check-secrets.outputs.has-secrets == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: './'
        github-comment: false
        github-deployment: false

  # Показываем инструкции если секреты не настроены
  deploy-instructions:
    name: Deployment Instructions
    runs-on: ubuntu-latest
    needs: check-secrets
    if: needs.check-secrets.outputs.has-secrets == 'false'
    
    steps:
    - name: Show deployment instructions
      run: |
        echo "🔐 Vercel deployment secrets not configured"
        echo ""
        echo "📋 To enable automatic deployment:"
        echo "1. Go to GitHub Repository Settings → Secrets and variables → Actions"
        echo "2. Add these secrets:"
        echo "   • VERCEL_TOKEN - from Vercel Dashboard → Settings → Tokens"
        echo "   • VERCEL_ORG_ID - run 'vercel env ls' in project"
        echo "   • VERCEL_PROJECT_ID - run 'vercel env ls' in project"
        echo ""
        echo "🚀 Manual deployment:"
        echo "   Visit: https://vercel.com/new/clone?repository-url=https://github.com/Richbanker/Finance-Mini-App"
        echo ""
        echo "✅ Your code is ready for deployment!"